#language: python
#python:
#  - "3.5"
#install:
#  - pip install pylint
#script:
#  - ./developer_utilities/validate_config.py
#  - ./developer_utilities/pylint_buildkit.py --hide-fixme
#  - ./developer_utilities/pylint_devutils.py --hide-fixme developer_utilities/
